spring.application.name=pickleball-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/pickleball_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Secret key MUST be at least 32 characters long
jwt.secret=pickleball_super_secret_key_minimum_32_chars
# 86400000 milliseconds = 24 hours token validity
jwt.expiration=86400000


server.port=8080


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

spring.web.cors.allowed-origins=http://localhost:3000